import 'package:genkit_google_genai/genkit_google_genai.dart';
import 'package:schemantic/schemantic.dart';
import 'package:google_cloud_firestore/google_cloud_firestore.dart';
import 'package:firebase_admin_sdk/firebase_admin_sdk.dart';
import '../tools/fitting_tool.dart';
import '../tools/catalog_tool.dart';
import 'fitting_room_flow.dart' show saveToStorage;
import '../ai.dart';

class SessionState {
  final String sessionId;
  SessionState(this.sessionId);

  DocumentReference<Map<String, dynamic>> get _doc {
    final firestore = FirebaseApp.instance.firestore();
    return firestore.collection('sessions').doc(sessionId);
  }

  Future<Map<String, dynamic>> getAll() async {
    try {
      final snap = await _doc.get();
      if (!snap.exists) return {};
      return snap.data() ?? {};
    } catch (_) {
      return {};
    }
  }

  Future<void> set(String key, dynamic value) async {
    try {
      await _doc.set({key: value}, options: const SetOptions.merge());
    } catch (_) {}
  }

  Future<dynamic> get(String key) async {
    final all = await getAll();
    return all[key];
  }
}

final getProductImageTool = ai.defineTool(
  name: 'getProductImage',
  description: 'get the URL or identifier for a product image',
  inputSchema: SchemanticType.from(
    jsonSchema: {
      'type': 'object',
      'properties': {
        'image_name': {'type': 'string'}
      },
      'required': ['image_name']
    },
    parse: (json) => json,
  ),
  outputSchema: SchemanticType.from(
    jsonSchema: {
      'type': 'object',
      'properties': {
        'image': {'type': 'string'}
      },
      'required': ['image']
    },
    parse: (json) => json,
  ),
  fn: (input, context) async {
    final imageName = input['image_name'] as String;
    return {'image': imageName};
  },
);

final stylistResponseSchema = SchemanticType.from(
  jsonSchema: {
    'type': 'object',
    'properties': {
      'outfits': {
        'type': 'array',
        'minItems': 3,
        'items': {
          'type': 'object',
          'properties': {
            'image': {
              'type': 'string',
              'description': 'GCS URL of a generated try-on fitting image, as generated by the fitting tool.'
            },
            'commentary': {
              'type': 'string'
            },
            'products': {
              'type': 'array',
              'minItems': 2,
              'maxItems': 5,
              'items': {
                'type': 'object',
                'properties': {
                  'title': {
                    'type': 'string'
                  },
                  'subtitle': {
                    'type': 'string'
                  },
                  'price': {
                    'type': 'number'
                  },
                  'id': {
                    'type': 'string'
                  }
                },
                'required': ['title', 'id']
              }
            }
          },
          'required': ['image', 'commentary', 'products']
        }
      }
    },
    'required': ['outfits']
  },
  parse: (json) => json,
);

const stylistInstructions = '''
You are a fashion stylist. Your goal is to suggest curated outfit combinations based on the user's location, occasion, and style preferences.

## The user's base image (face / identity source)

There is exactly ONE image that represents the user. You will receive its GCS URI in the prompt reminders. Use this GCS URI verbatim.

This base image is your only source of the user's face and identity. Use it as the `user_image` argument every single time you call the `fitting_tool`. Do NOT use:
- any GCS URI containing generated outfits (those are outputs of previous calls)
- any other image you find in context

If you are about to call `fitting_tool` and the user_image is anything other than the pinned source, STOP and re-check.

## Workflow

1. Call the `listProducts` tool first to get the full list of available products in the catalog.
2. Suggest 3 distinct outfit combinations using only products from that catalog. Each outfit should offer a different style direction for the same location/occasion.
3. For each outfit:
   - Call `getProductImage` for each product in the outfit, to fetch its image name.
   - Call `fitting_tool` ONCE for the outfit, with:
     - `user_image` = the GCS URI of the user photo provided in the prompt reminders
     - `accessories` = the list of product image names you just fetched
4. Return the structured outfits response.
''';

final stylistFlow = ai.defineFlow(
  name: 'stylistFlow',
  inputSchema: SchemanticType.from(
    jsonSchema: {
      'type': 'object',
      'properties': {
        'prompt': {'type': 'string'},
        'userId': {'type': 'string'},
        'sessionId': {'type': 'string'},
        'userImageBase64': {'type': 'string'},
        'userImageGcsUrl': {'type': 'string'}
      },
      'required': ['prompt', 'userId', 'sessionId']
    },
    parse: (json) => json,
  ),
  outputSchema: stylistResponseSchema,
  fn: (input, context) async {
    final prompt = input['prompt'] as String;
    final userId = input['userId'] as String;
    final sessionId = input['sessionId'] as String;
    final userImageBase64 = input['userImageBase64'] as String?;
    final userImageGcsUrl = input['userImageGcsUrl'] as String?;

    final state = SessionState(sessionId);

    // 1. Process base image tracking
    if (userImageGcsUrl != null && userImageGcsUrl.isNotEmpty) {
      await state.set('user_base_image_str', userImageGcsUrl);
    } else if (userImageBase64 != null && userImageBase64.isNotEmpty) {
      final userUri = await saveToStorage(userImageBase64, 'users/$userId/uploads');
      await state.set('user_base_image_str', userUri);
    }

    // 2. Build model prompt with state hints
    final savedBaseImage = await state.get('user_base_image_str') as String?;
    String reminderText = '';
    if (savedBaseImage != null && savedBaseImage.isNotEmpty) {
      reminderText = '\n\nREMINDER: ALWAYS use this GCS URI as user_image when calling fitting_tool. Do NOT use any other image. URI: $savedBaseImage';
    }

    final prevProducts = await state.get('previously_used_products') as List?;
    String prevProductsText = '';
    if (prevProducts != null && prevProducts.isNotEmpty) {
      prevProductsText = '\n\nIMPORTANT: You previously suggested these product IDs: ${prevProducts.join(', ')}. You MUST pick DIFFERENT complementary products this time to give the user fresh, new outfit ideas. Do NOT reuse any of those product IDs.';
    }

    final fullPrompt = '$prompt$reminderText$prevProductsText';

    final response = await ai.generate(
      model: googleAI.gemini('gemini-3.1-pro-preview'),
      system: stylistInstructions,
      prompt: fullPrompt,
      tools: [listProductsTool, fittingTool, getProductImageTool],
      outputSchema: stylistResponseSchema,
    );

    // 3. Save selected products to state for context exclusion on future turns
    final output = response.output as Map<String, dynamic>?;
    if (output != null && output.containsKey('outfits')) {
      final outfits = output['outfits'] as List?;
      if (outfits != null) {
        final List<String> productIds = [];
        for (final outfit in outfits) {
          final products = outfit['products'] as List?;
          if (products != null) {
            for (final prod in products) {
              final id = prod['id'] as String?;
              if (id != null && id.isNotEmpty && !productIds.contains(id)) {
                productIds.add(id);
              }
            }
          }
        }
        if (productIds.isNotEmpty) {
          await state.set('previously_used_products', productIds);
        }
      }
    }

    return output ?? {};
  },
);
